### ISSUE TITLE
sources corrupted? can't compile

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#18]
when i download clean v35.5 sources, and try to open it in vb6, 
i get a lot of errors like
`
"Error during load. Refer to ~\blackd\frmMain.log for details."`
  ( http://prntscr.com/65yksx ) 

while i can still successfully "Start with full compile", compile, edit, and debug, version 34.8 sources without problem on the same computer. 

The error logs contains:
`
'0' could not be loaded
Line 0: The file C:\Users\hanshenrik\Desktop\OT\tibianic\tibia\blackd\frmMain.frm could not be loaded.
`

somehow, looks like the sources posted on github are corrupted, or maybe *.OBJ files was more important than i realized? 

to reproduce: 
go to https://github.com/blackdtools/Blackd-Proxy-CLASSIC/tree/98df19962cb6bbb6f824fde22710ff898c009f36

then press "Download ZIP"

then download, and extract to a new folder, then try to open that in VB6.. 

theory 1:the *.OBJ files was more important than i realized, and VB can't open the source files without them????  (i think theory 2 is more likely)
theory 2: git with the .gitattribute :
`
#Auto detect text files and perform LF normalization
- text=auto
  ` 

that text=auto 
is converting it to a line-ending that does not agree with VB6, and VB6 errors out trying to read the files
i suggest replacing 
`* text=auto`
with
`* binary`
, push, and download zip, and try to open again, hopefully that should fix the errors =/

**Comment by blackdtools** [comment]
I don’t really know. An obj file should not be necessary, but Microsoft makes big fails often so I don’t really know. I will  try removing the ignore from .obj files now, then I will upload my local files – they are still opening and compiling correctly here.
- Daniel Peña Vázquez ( www.blackdtools.com http://www.blackdtools.com/  )

LEGAL NOTICE - ABOUT CONFIDENTIAL INFORMATION

This message and its contents may contain confidential information and its non-authorised use is prohibited by law. If you are not the intended recipient of this email or do not wish to receive marketing information, please advise the sender of the fact using the same, or other, means and delete this message and its contents from your system without copying, forwarding or revealing the contents of the message to any other person. Any information, opinion,conclusion, recommendation, etc. contained in this message and which is unrelated to the business activity of DANIEL PEÑA VAZQUEZ and/or issued by unauthorised personnel, shall be considered unapproved by DANIEL PEÑA VAZQUEZ. DANIEL PEÑA VAZQUEZ implements control measures to ensure, as far as possible, the security and reliability of all its electronic correspondence. However, does not guarantee that emails are virus-free or that documents have not be altered and takes no responsibility in this respect.

NOTA LEGAL - CLÁUSULA DE CONFIDENCIALIDAD

Este mensaje y sus anexos pueden contener información confidencial, por lo que se informa de que su uso no autorizado está prohibido por la ley. Si Vd. considera que no es el destinatario pretendido por el remitente o no desea recibir información comercial, por favor póngalo en su conocimiento por esta misma vía o por cualquier otro medio elimine esta comunicación y los anexos de su sistema, sin copiar, remitir o revelar los contenidos del mismo a cualquier otra persona. Cualquier información, opinión, conclusión, recomendación, etc. contenida en el presente mensaje no relacionada con la actividad empresarial de DANIEL PEÑA VAZQUEZ y/o emitida por persona sin capacidad para ello, deberá considerarse como no proporcionada ni aprobada por DANIEL PEÑA VAZQUEZ. DANIEL PEÑA VAZQUEZ pone los medios a su alcance para garantizar la seguridad y ausencia de errores en la correspondencia electrónica, pero no puede asegurar la inexistencia de virus o la no alteración de los documentos transmitidos electrónicamente, por lo que declina cualquier responsabilidad a este respecto.

De: divinity76 [mailto:notifications@github.com] 
Enviado el: lunes, 16 de febrero de 2015 21:20
Para: blackdtools/Blackd-Proxy-CLASSIC
Asunto: [Blackd-Proxy-CLASSIC] sources corrupted? can't compile (#18)

when i download clean v35.5 sources, and try to open it in vb6, 
i get a lot of errors like

"Error during load. Refer to ~\blackd\frmMain.log for details."
( http://prntscr.com/65yksx ) 

while i can still successfully "Start with full compile", compile, edit, and debug, version 34.8 sources without problem on the same computer. 

The error logs contains:

'0' could not be loaded
Line 0: The file C:\Users\hanshenrik\Desktop\OT\tibianic\tibia\blackd\frmMain.frm could not be loaded.

somehow, looks like the sources posted on github are corrupted, or maybe *.OBJ files was more important than i realized? 

to reproduce: 
go to https://github.com/blackdtools/Blackd-Proxy-CLASSIC/tree/98df19962cb6bbb6f824fde22710ff898c009f36

then press "Download ZIP"

then download, and extract to a new folder, then try to open that in VB6.. 

theory 1:the *.OBJ files was more important than i realized, and VB can't open the source files without them???? (i think theory 2 is more likely)
theory 2: git with the .gitattribute :
`
#Auto detect text files and perform LF normalization
-   text=auto ` that text=auto is converting it to a line-ending that does not agree with VB6, and VB6 errors out trying to read the files i suggest replacing 
-   text=auto with
-   binary , push, and download zip, and try to open again, hopefully that should fix the errors =/

**Comment by doda4ever** [comment]
It is not opening for my too.

**Comment by divinity76** [comment]
this has been fixed (i dont know when), closing issue

**Comment by Nrated** [comment]
Maybe try opening vb studio as admin ; p
