### ISSUE TITLE
"MSG THAT CONTAINS..." broken for 7.6

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#28]
i can't get "MSG THAT CONTAINS..." Action: to activate for PMs on 7.6.. does it work for anyone else? on any version?

**Comment by divinity76** [comment]
Heh, it works today :o i have no idea what went wrong, but it works now.. never mind ^^

**Comment by Nrated** [comment]
Yeah but still...few messages still aren't detectable, like orange default[11]
