### ISSUE TITLE
(7.6) "setAny" (attack any creature) cavebot command does not work

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#32]
with 

``` vb
resetKill
setAny
```

the cavebot will attack absolutely nothing and nobody, as far as i can see..
even if you do

``` vb
resetKill
setAny
setPriority Demon:+1
```

it will not attack Demon.

**Comment by Nrated** [comment]
I don't think its working this way.
SetAny, SetFriendly, SetVeryFriendly
I think it is something related to FriendlyMode which determines whether you keep attacking monsters when other players are on the screen, or not(but i might be wrong)

**Comment by divinity76** [comment]
damn, looks like you're right. well, i just made a pull request for "seMeleeKill *" -> makes everything a target, see https://github.com/blackdtools/Blackd-Proxy-CLASSIC/pull/40

**Comment by Nrated** [comment]
Nice job man!! I have one suggestion though: this function should be named more like "setKillAll" or "setMeleeKillAll" something that would refer to actual purpose just by the name : D

**Comment by divinity76** [comment]
or maybe "SetBot KillAll=1" like we have "SetBot LootAll=1", i don't know. Daniel, any comments?

**Comment by divinity76** [comment]
or maybe "SetBot KillAll=1" like we have "SetBot LootAll=1", i don't know. Daniel, any comments?

oh, and "SetBot TerminateEveryone" is Skynet-approved

and for ignore/whitelist: ComeWithMeIfYouWantToLive Name
joking :p

**Comment by blackdtools** [comment]
Thank you for your fedback and improvements. Any syntax option there will be ok.
