### ISSUE TITLE
8.60 connection is broken?

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#49]
i downloaded tibia 8.60,
and using blackd proxy 37.1 for Tibia 8.6, i can't connect to _any_ 8.6 server. but when i use the IP changer from https://otland.net/threads/otland-ip-changer.134369/ , i can connect just fine. i tried several 8.60 servers from http://otservlist.org/ , and it was the same with all of them.

the log from proxy is

```
#client1 connected (IP 127.0.0.1) , forwarding to 127.0.0.1:7171 #
#server1 connected#
#server1 closed (by server) #
```

, first it connects to the server, then instantly disconnect, and the tibia client says
"Error: Disconnected from server. (200002)"

to reproduce:

download & install tibia 860 from here http://remeresmapeditor.com/marklar.php?clients

download & start 8.60 server from here https://github.com/opentibia/server/releases  
(OR just find a random 8.60 server from http://otservlist.org/ )

start 860 from blackd, with settings: ot server ip: 127.0.0.1

connect with username "tibia" and password "tibia"
- With BlackD Proxy, you'll get "error: disconnected from server", 
  but other IP changers, you can connect normally.

**Comment by divinity76** [comment]
funfact, Tibia 860 is the most popular OT client version, as most OT servers active today run for 860 client.  thus, a fix for 860 would probably cause more users :)  think you can take a look, Daniel?

**Comment by blackdtools** [comment]
Yes, it looks like I forgot obtaining the address of RSA key for that popular ot server version. Well, I obtained it and I added it. It is untested, but I am almost sure it should work.

**Comment by divinity76** [comment]
ok, i confirmed, that fixed the problem :)
