### ISSUE TITLE
cabebot fails to walk up ladders in 7.6

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#6]
while the cavebot is capable of walking down ladders, and walking up stairs, it refuse to walk up ladders in tibia 7.6.. screenshot  https://cdn.mediacru.sh/z/zUlRwmYi4kR2.jpe

**Comment by divinity76** [comment]
can someone try to confirm/reproduce this?

**Comment by blackdtools** [comment]
I don't remember that kind of ladder existing in standard Tibia 7.6 ... Blackd Proxy is only designed for standard tibia clients (with standard tiles) Anyways, if an user is playing an ot server with modified tibia.dat then he can edit config760\config.ini and edit/add some tiles at [tileIDs] Just in case the ot server is using a tibia.dat of a modern version you can try using the following values:

AditionalStairsToUpFloor=AC 07,AE 07,AA 07,94 08,96 08,90 08,92 08,03 1B,FF 1A,FD 1A,78 1D,76 1D,58 03,57 03,B7 07,7A 1D,7C 1D
AditionalStairsToDownFloor=36 1D,62 1D,64 03,34 1D,35 1D,6A 03
AditionalRequireRope=56 43,A5 01
AditionalRequireShovel=63 03

**Comment by divinity76** [comment]
oh, that's right, it's a modified tibia.dat and tibia.spr , that's probably it! ill add 
AditionalStairsToUpFloor=B0 0C and see if its still working 

(to make matters even worse, it's 1 of those OTs with a completely custom client, based on  https://github.com/edubart/otclient  , i just copied the .spr / .dat to the real 7.6 client, reverse-engineered the modified login protocol - which spews swears words like "fuck you asshole" to any1 looking at it :p -  made BlackD Proxy fix the login protocol at runtime, and voila!)

**Comment by blackdtools** [comment]
ok, nice!

**Comment by divinity76** [comment]
speaking of, "Aditional", it is not an English word, but Additional is
