### ISSUE TITLE
[feature request] can we get a OnReconnectGoTo for the cavebot? 

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#65]
as far as i know, there is no way to specify what to do when it has reconnected from server restart/connection drop; it simply opens the first backpack (if any); sometimes i would like to do more than just opening the first backpack, like opening the loot backpack;

**Comment by Nrated** [comment]
If u want to make something like this without editing source than you should play with $played$
Can't remember syntax though
IfTrue($played$#string=#0h 0m 1s) goto $nlineoflabel:my_loop$
If u want to open bp in cavebot:

```
fastExiva _numofcontainer = 00
#00 = first opened container
fastExiva _bpid = 33 0B
fastExiva _summonlootBP = sayMessage exiva #$_bpid$ 03
:my_loop
waitX 1
#place lootBP on the first slot in your BP using exiva #ID SLOT which will summon your
#LootBP to BackPack Slot(03). Here:
$_summonlootBP$
sayMessage exiva > 82 FF FF 40 00 00 $_bpid$ 00 $_numofcontainer$
#idont remember exact syntax of iftrue but u will know what I mean
IfTrue($countitems:SOME_ID$#number<#1) goto $nlineoflabel:my_loop$
#iftrue is supposed to determine If your loot bp is already opened. It checks for an 
#items that are only In loot bp, or you could look for items from your mainBP
#(since this packet will close mainBP and open Loot BP on top of it: container 00)
#keep doing whatever you want
```

You can also just place exact BP ID's in script without doing fancy things like $_summonlootBP$
Im just bored xD Probably it would be easier to do with source xD

**Comment by divinity76** [comment]
yeah thanks! "open backpack" was exactly my problem ^^
