### ISSUE TITLE
[7.6] Problem with connecting under windows 8.1

### ISSUE THREAD

**Issue by Nrated** [blackdtools/Blackd-Proxy-CLASSIC#69]
Well...so I'm having a rly hard time trying to log into the game...70% of the time after typing my password, server returns "disconnected". It is really troublesome and I don't know how to solve this

**Comment by blackdtools** [comment]
I will suppose you are playing Tibia 10.91, else please let me know the version.

Well, Tibia 10.91 login system changed and I had to build a new parser for it. Real Tibia login server does not send subpackets in a same order anymore. It is a bit random now, and I probably missed some cases. First of all please ensure you have latest version because I already added some additional cases. Then, if you still get such bug then please enable packets logs during login and send me the packets you received from server in case when bot fails to connect. That way I can improve the new parser a bit more.

**Comment by Nrated** [comment]
Nope its old tibia 7.6 : P im not having this issue using my PC with win7 : P
proxy log says that connection was closed, nothing more. For now Login Bypass works fine

**Comment by Nrated** [comment]
Can u also tell me how to reverse changes with lighthack? Since ver.33-35 it's flashing all the time instead of keeping 100% light all the time

**Comment by divinity76** [comment]
@Nrated idk what is wrong with the LIGHT_NOP & co code for 760, but something's definitely wrong. guess somebody has to fix it.. 
In the meantime, check this out

``` vb
      ' Tibia.exe+48A83 - 8B 48 74              - mov ecx,[eax+74]
      ' is at memory location 00448A83, change to:
      ' Tibia.exe+48A83 - 90                    - nop 
      ' Tibia.exe+48A84 - 90                    - nop 
      ' Tibia.exe+48A85 - 90                    - nop 
      ' for whatever reason, before ecx is modified here, ecx always seem to have the value 255 :D
      ' now every creature always have light value 255
      ' 1 problem: max needed light is about 100,
      '  and any light above 100 just increase CPU usage, thus light 255 is bad for FPS,
      ' it use more CPU to create 30 fps on my pc with "every creature have 255 light",
      ' i tried "every creature have like 10,000 light", and the fps dropped to 2 FPS and 100% cpu!
     ' so this hack could be improved...
```

this will give you perfect light hack. open tibia.exe in a hex editor, go to offset 48A83 (hex offset), or offset 297603 (decimal offset), there you will find the bytes "8B 48 74", change it to "90 90 90", and you will have permanent never-changing light of 255 for every creature (and possibly items, i'm not sure about that) ... note the cpu warning tho, if you want 100 light for every creature, you need to do a JMP NEAR to a nearby place with 5x unused nops (its not far away), then use a JMP LONG to some unused space at the end of tibia.exe (there's lots of them - but beware, some places LOOKS unused, but is actually the containment area of static variables) - anyway once you find a suitable place, you can do mov ecx,0x64 ; jmp long 48A86; and you wouldn't have the cpu issue

... feel free to improve it, i cba

**Comment by Nrated** [comment]
assembler is way beyond me xD

**Comment by divinity76** [comment]
@Nrated i thought it might be, thus i added instructions for using a hex editor as well. a hex editor should be easy to figure out when you're capable of stuff like this https://github.com/blackdtools/Blackd-Proxy-CLASSIC/pull/62/files

**Comment by Nrated** [comment]
yeah I will try this thing later, thanks anyways!:  )

**Comment by Nrated** [comment]
```
#server1 connected#
SERVER1<( hex ) 5D 00 14 1A 00 31 0A 57 69 74 61 6D 79 20 6E 61 20 4D 61 7A 75 72 73 6B 69 6D 20 37 2E 36 21 64 02 06 00 47 65 74 20 4D 65 0C 00 4D 61 7A 75 72 73 6B 69 20 4F 54 53 1F BA 53 58 03 1C 0A 00 59 6F 75 20 4F 77 65 20 4D 65 0C 00 4D 61 7A 75 72 73 6B 69 20 4F 54 53 1F BA 53 58 03 1C 00 00 
SERVER1<( hex ) 5D 00 14 1A 00 31 0A 57 69 74 61 6D 79 20 6E 61 20 4D 61 7A 75 72 73 6B 69 6D 20 37 2E 36 21 64 02 06 00 47 65 74 20 4D 65 0C 00 4D 61 7A 75 72 73 6B 69 20 4F 54 53 7F 00 00 01 80 3E 0A 00 59 6F 75 20 4F 77 65 20 4D 65 0C 00 4D 61 7A 75 72 73 6B 69 20 4F 54 53 7F 00 00 01 80 3E 00 00 
#server1 closed (by server) #
```

Is it normal to receive login packet two times?

any suggestions? I'm getting two different login packets. One from server and the second one from blackd socket...(IP 127.0.0.1 and different amount of premium days)

**Comment by blackdtools** [comment]
I don't really know. Maybe it is a bug in my code for login 7.6. You would have to debug DoMainLoopLogin, LearnFromServerLogin and PacketIPchange2.
But maybe it is only a bug with the code of your ot server. Hard to know.

**Comment by Nrated** [comment]
Ok thanks for ideas : D I'll look through those functions

**Comment by Nrated** [comment]
I have fixed this temporary by commenting one line in SckServer_Close()

``` vb.net
'sckServer(Index).Close
```

for now its working fine. earlier server after closing sckserver wasn't moving forward to sckgameclient/server ; p im going to check this thing later
