### ISSUE TITLE
since 10.73 update, cavebot is disconnecting people

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#7]
since the 10.73 update, in the forums, people are complaining that they're being disconnected when using cavebot+MC
( http://www.blackdtools.net/showthread.php?61963-Updated-for-Tibia-10-73&p=446851#post446851 / http://www.blackdtools.net/showthread.php?61963-Updated-for-Tibia-10-73&p=446858#post446858 )
I guess error is about this  https://github.com/blackdtools/Blackd-Proxy-CLASSIC/pull/1 (it highlights a code line from MC1's cavebot, highlight a line that doesn't exist in the GUI's current list, as it list the cavebot script from MC2, gets an error, and disconnects), however that's just my best guess, i have't actually investigated it,
Anyway, Until someone actually investigate this, i suggest disabling the code

``` vb
 frmCavebot.lstScript.ListIndex = currLineNumber - 1 'why -1? ListIndex start at 0, currLineNumber start at 1
```

and make a quickfix release, (or you could investigate it and fix it ofc, maybe im wrong, who knows. unfortunately im busy with marriage papers these days)

**Comment by blackdtools** [comment]
ok, I think I fixed it now.
