### ISSUE TITLE
Cavebot sometimes incorrectly detects GM's when going down floors

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#80]
there is some weird bug wherein this error will occur:
`mychar closed with this message: Client closed - condition onGMcloseConnection was activated: GM Tsar`

when blackd proxy have seen GM Tsar when leaving depot, and cavebot has onGMcloseConnection, it may sometimes (completely incorrectly!!) believe that GM Tsar is nearby when the cavebot is changing floor down!

**Comment by Nrated** [comment]
Whoaaaaah I just logged in to my e-mail account and from what I can see there's a lot of new things here! Keep it up mate

**Comment by divinity76** [comment]
^ i started playing again ^^

anyway, i found out that it's actually a bug in this OT, it will sometimes send info about players which is like 100 SQM away when walking up/down floors. like here, i am very very far away from the GM in question, yet the server sends me info about everyone in DP every time i go down a floor. i have no idea why. weird OT custom code bug.

```
         Case &H62

          ' we already knew his ID + include some info
          tempID = FourBytesDouble(packet(pos + 2), packet(pos + 3), packet(pos + 4), packet(pos + 5))
          AddID_HP idConnection, tempID, packet(pos + 6) 'update hp
          nameofgivenID = GetNameFromID(idConnection, tempID)
```
