### ISSUE TITLE
activating cavebot should reset exp/h

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#83]
as far as i know, there's currently no way to reset exp/h meter, i think it would be useful if exp/h counter reset whenever you press the "activate cavebot" button

**Comment by Nrated** [comment]
Only if it would be optional
Maybe MsgBox at start asking if you want to reset exp counter?(YES/NO)

**Comment by blackdtools** [comment]
Yes, I think it should be an optional feature. But I prefer to avoid MsgBox because it freezes everything.

**Comment by Nrated** [comment]
Yeah, you're right. Normal checkbox with description would be good enough

**Comment by Nrated** [comment]
You can also put it at the beginning of the script if you're too lazy to compile ; D

```
setBot AllowRepositionAtStart=0
sayMessage exiva expreset
:loop
#put your script here
#put your script here
#put your script here
gotoScriptLine $nlineoflabel:loop$
```

@down
No need to be sarcastic xD

**Comment by divinity76** [comment]
oh i didn't know about that command! kk nice ^^

**Comment by divinity76** [comment]
oh and i think this is the perfect job for
`fastExiva expreset`
^^ since it's that easy, nvm, closing "issue"
