### ISSUE TITLE
[Question]Tibia title info doesn't seem to work on tibia 7.6 lately

### ISSUE THREAD

**Issue by Neorisen** [blackdtools/Blackd-Proxy-CLASSIC#89]
Hi,
I don't know what happened lately in blackdproxy but I can't display anything in tibia title while playing on tibia 7.6. Has anyone encountered this problem recently?
Maybe it's related to changes in the newest tibia protocols or that's just because of windows 10...

**Comment by divinity76** [comment]
there are some old releases available at https://github.com/blackdtools/Blackd-Proxy-CLASSIC/releases?after=v42.0  , could you check if it works in older versions or not for you?

**Comment by Neorisen** [comment]
Shame on me xD I checked source code and it seems that I just forgot about stealth frame and "exp here" check 😄

**Comment by divinity76** [comment]
so.. if this issue is invalid, it should be closed~ (i can't do that, but you @Neorisen can close it because you're the issue owner, and @blackdtools  can close it because he's the project owner)

**Comment by Neorisen** [comment]
@divinity76 okay, okay
